name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 as test compile
    - name: Run tests
      run: rebar3 cover_tests
    - name: Send test coverage report
      run: rebar3 as test codecov analyze
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dialyzer:
    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v3
    - name: Run dialyzer
      run: rebar3 dialyzer

  xref_and_hank:
    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v3
    - name: Run xref
      run: rebar3 xref
    - name: Run dead code cleaner (Hank)
      run: rebar3 find_dead_code

  erlfmt:
    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v3
    - name: Run erlfmt
      run: rebar3 format_check
