name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 ct --sname=ct1

  dialyzer:
    runs-on: ubuntu-latest

    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer

  xref:
    runs-on: ubuntu-latest

    container:
      image: erlang:23

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run xref
      run: rebar3 xref
