name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    name: Tests-OTP${{matrix.otp}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        otp: ['28', '27', '26']
        rebar3: ['3.25.0']
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: ${{ matrix.rebar3 }}
    - run: rebar3 as test compile
    - run: rebar3 cover_tests
    - run: rebar3 as test codecov analyze
    - uses: codecov/codecov-action@v5
      with:
        files: codecov.json
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  static_tools:
    name: Static-OTP${{matrix.otp}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        otp: ['28', '27', '26']
        rebar3: ['3.25.0']
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: ${{ matrix.rebar3 }}
    - run: rebar3 xref
    - run: rebar3 dialyzer
    - run: rebar3 format_check
    - run: rebar3 ex_doc
